language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"

install:
    - python ./setup.py install
    - pip install -r requirements-test.txt --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements-test-py26.txt --use-mirrors; fi

script: py.test
sudo: false
