language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

install:
    - python ./setup.py install
    - pip install -r requirements-test.txt --use-mirrors
script: py.test
